name: Kata16

on:
  push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v1
      with:
        java-version: 13
    - name: Gradle Command
      uses: eskatos/gradle-command-action@v1
      with:
        gradle-version: rc
        arguments: build
